# Psion
- name: Psion - Consumer Devices
  devices:

  # Series 3
  - name: Series 3
    variants:

    - name: V1.77F
      id: psion3
      bios: 177f
      description: Psion Series 3
      languages:
      - en-GB
      display:
        width: 240
        height: 80
        scale: 2
      roms:
      - name: 3504-3001-01_19-11-91v1.77f_eng.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3/s3_v1.77f_eng/s3_v1.77f_eng1.bin
      - name: 3504-3002-01_19-11-91v1.77f_eng.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3/s3_v1.77f_eng/s3_v1.77f_eng2.bin

    - name: V1.91F
      id: psion3
      bios: 191f
      description: Psion Series 3
      languages:
      - en-GB
      - fr-FR
      - de-DE
      - es-ES
      - it-IT
      display:
        width: 240
        height: 80
        scale: 2
      roms:
      - name: s3_v1.91f_multi.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3/s3_v1.91f_multi/s3_v1.91f_multi.bin

    - name: V1.80F
      id: psion3
      bios: 180f
      description: Psion Series 3
      languages:
      - en-GB
      - fr-FR
      - de-DE
      - it-IT
      display:
        width: 240
        height: 80
        scale: 2
      roms:
      - name: s3_v1.80f_multi.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3/s3_v1.80f_multi/s3_v1.80f_multi.bin

  # Series 3s
  - name: Series 3s
    variants:

    - name: V1.91F
      id: psion3s
      bios: 191f
      description: Series 3 variant with built-in Sheet program
      languages:
      - en-GB
      display:
        width: 240
        height: 80
        scale: 2
      roms:
      - name: s3_v1.91f_eng.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3/s3_v1.91f_eng/s3_v1.91f_eng.bin

  # Series 3a (1MB ROM)
  - name: Series 3a (1MB ROM)
    variants:

    - name: V3.22F
      id: psion3a
      bios: 322f
      description: 1MB ROM variant
      languages:
      - en-GB
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: s3a_v3.22f_eng.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3a/s3a_v3.22f_eng/s3a_v3.22f_eng.bin

  # Series 3a (2MB ROM)
  - name: Series 3a (2MB ROM)
    variants:

    - name: V3.40F
      id: psion3a2
      bios: 340f
      description: 2MB ROM variant with built-in Spell and Patience programs
      languages:
      - en-GB
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: s3a_v3.40f_eng.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3a/s3a_v3.40f_eng/s3a_v3.40f_eng.bin

    - name: V3.40F
      id: psion3a2_it
      bios: 340f
      description: 2MB ROM variant with built-in Spell and Patience programs
      languages:
      - it-IT
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: s3a_v3.40f_ita.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3a/s3a_v3.40f_ita/s3a_v3.40f_ita.bin

    - name: V3.40F
      id: psion3a2_us
      bios: 340f
      description: 2MB ROM variant with built-in Spell and Patience programs
      languages:
      - en-US
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: s3a_v3.40f_usa.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3a/s3a_v3.40f_usa/s3a_v3.40f_usa.bin

    - name: V3.41F
      id: psion3a2_de
      bios: 341f
      description: 2MB ROM variant with built-in Spell and Patience programs
      languages:
      - de-DE
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: s3a_v3.41f_deu.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3a/s3a_v3.41f_ger/s3a_v3.41f_ger.bin

    - name: V3.43F
      id: psion3a2_ru
      bios: 343f
      description: 2MB ROM variant with built-in Spell and Patience programs
      languages:
      - ru-RU
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: s3a_v3.43f_rus.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3a/s3a_v3.43f_rus/s3a_v3.43f_rus.bin

  - name: Siena
    variants:

    - name: V4.20F
      id: siena
      bios: 420f
      description: Psion Siena
      languages:
      - en-GB
      display:
        width: 240
        height: 160
        scale: 1
      roms:
        - name: vine_v4.20f_eng.bin
          url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Siena/vine_v4.20f_eng/vine_v4.20f_eng.bin

    - name: V4.21F
      id: siena_fr
      bios: 421f
      description: Psion Siena
      languages:
      - fr-FR
      display:
        width: 240
        height: 160
        scale: 1
      roms:
      - name: vine_v4.21f_frn.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Siena/vine_v4.21f_fre/vine_v4.21f_fre.bin

  # Series 3c
  - name: Series 3c
    variants:

    - name: V5.20F
      id: psion3c
      bios: 520f
      languages:
      - en-GB
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: oak_v5.20f_eng.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3c/oak_v5.20f_eng/oak_v5.20f_eng.bin

  # Series 3mx
  - name: Series 3mx
    variants:

    - name: V6.16F
      id: psion3mx
      bios: 616f
      languages:
      - en-GB
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: maple_v6.16f_uk.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3mx/maple_v6.16f_eng/maple_v6.16f_eng.bin

    - name: V6.17F
      id: psion3mx_nl
      bios: 617f
      languages:
      - nl-NL
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: maple_v6.17f_nl.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3mx/maple_v6.17f_nl/maple_v6.17f_nl.bin

    - name: V6.20F
      id: psion3mx_fr
      bios: 620f
      languages:
      - fr-FR
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: maple_v6.20f_fre.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3mx/maple_v6.20f_fre/maple_v6.20f_fre.bin

  # Series 5mx
  - name: Series 5mx
    variants:

    - name: 1.05(250)
      id: psion5mx
      bios: "250"
      languages:
      - en-GB
      display:
        width: 695
        height: 305
        scale: 1
      touchscreen: True
      roms:
      - name: s5mx_uk10_v250.rom
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/5mx/5mx_v1.05(250)_eng/5mx_v1.05(250)_eng.bin
      artwork:
      - name: psion5mx.zip
        md5: 251cd0d18026469dcf64572388b333fb
        url: https://scratch.jbmorley.co.uk/mame/artwork/psion5mx.zip

    - name: 1.05(255)
      id: psion5mx
      bios: "255a"
      languages:
      - en-GB
      display:
        width: 695
        height: 305
        scale: 1
      touchscreen: True
      roms:
      - name: s5mx_uk10_v255.rom
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/5mx/5mx_v1.05(255)_10_eng/5mx_v1.05(255)_10_eng.bin
      artwork:
      - name: psion5mx.zip
        md5: 251cd0d18026469dcf64572388b333fb
        url: https://scratch.jbmorley.co.uk/mame/artwork/psion5mx.zip

    - name: 1.05(255) (16MB)
      id: psion5mx
      bios: "255"
      languages:
      - en-GB
      display:
        width: 695
        height: 305
        scale: 1
      touchscreen: True
      roms:
      - name: s5mx_uk16_v255.rom
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/5mx/5mx_v1.05(255)_16_eng/5mx_v1.05(255)_16_eng.bin
      artwork:
      - name: psion5mx.zip
        md5: 251cd0d18026469dcf64572388b333fb
        url: https://scratch.jbmorley.co.uk/mame/artwork/psion5mx.zip

    - name: 1.05(260) (16MB)
      id: psion5mx
      bios: "260"
      languages:
      - en-GB
      display:
        width: 695
        height: 305
        scale: 1
      touchscreen: True
      roms:
      - name: s5mx_uk16_v260.rom
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/5mx/5mx_v1.05(260)_eng/5mx_v1.05(260)_eng.bin
      artwork:
      - name: psion5mx.zip
        md5: 251cd0d18026469dcf64572388b333fb
        url: https://scratch.jbmorley.co.uk/mame/artwork/psion5mx.zip

- name: Psion - Enterprise Devices
  devices:

  # Workabout
  - name: Workabout
    variants:

    - name: V0.24B
      id: psionwa
      bios: 024b
      languages:
      - en-GB
      display:
        width: 240
        height: 100
        scale: 1
      roms:
      - name: w1_v0.24b.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Workabout/w1_v0.24b_eng/w1_v0.24b_eng.bin

    - name: V1.00F
      id: psionwa
      bios: 100f
      languages:
      - en-GB
      display:
        width: 240
        height: 100
        scale: 1
      roms:
      - name: w1_v1.00f.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Workabout/w1_v1.00f_eng/w1_v1.00f_eng.bin

    - name: V2.40F
      id: psionwa
      bios: 240f
      languages:
      - en-GB
      display:
        width: 240
        height: 100
        scale: 1
      roms:
      - name: w1_v2.40f.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Workabout/w1_v2.40f_eng/w1_v2.40f_eng.bin

  # Workabout MX
  - name: Workabout MX
    variants:

    - name: V7.20F
      id: psionwamx
      bios: 720f
      languages:
      - en-GB
      display:
        width: 240
        height: 100
        scale: 1
      roms:
      - name: w2mx_v7.20f.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/WorkaboutMX/w2mx_v7.20f_eng/w2mx_v7.20f_eng.bin

# Acorn
- name: Acorn
  devices:

  # Pocket Book
  - name: Acorn Pocket Book
    variants:

    - name: V1.91F
      id: pocketbk
      bios: 191f
      languages:
      - en-GB
      display:
        width: 240
        height: 80
        scale: 2
      roms:
      - name: pb_v1.91f_acn.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3/pb_v1.91f_acn/pb_v1.91f_acn.bin
      - name: acspell.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3/pb_v1.91f_acn/acspell.bin

  # Pocket Book II
  - name: Acorn Pocket Book II
    variants:

    - name: V1.30F
      id: pocketbk2
      bios: 130f
      languages:
      - en-GB
      display:
        width: 480
        height: 160
        scale: 1
      roms:
      - name: pb2_v1.30f_acn.bin
        url: https://github.com/explit28/Psion-ROM/raw/refs/tags/2026-05-27/Series3a/pb2_v1.30f_acn/pb2_v1.30f_acn.bin
